#!/usr/bin/env python3
"""Domus agent usage tracker.

Reads Claude Code and Codex session transcripts already on disk (zero model
tokens spent) and aggregates per-agent / per-project token usage into a
SQLite or Neon Postgres database (controlled by DATABASE_URL env var).

Usage:
  python scripts/agent-usage.py collect                   # balanced incremental ingest
  python scripts/agent-usage.py collect --platform codex  # ingest Codex only
  python scripts/agent-usage.py collect --max-updates 80  # bounded balanced batch
  python scripts/agent-usage.py report                    # summary tables
  python scripts/agent-usage.py report --agent security-reviewer
"""

import argparse
import json
import os
import sqlite3
import uuid
from pathlib import Path

from dotenv import load_dotenv

try:
    import psycopg
except ImportError:  # pragma: no cover - only needed when DATABASE_URL points to Postgres
    psycopg = None

HOME = Path.home()
ROOT = Path(__file__).parent.parent
DB_PATH = HOME / ".domus" / "usage.db"
CLAUDE_PROJECTS = HOME / ".claude" / "projects"
CODEX_SESSION_DIRS = [HOME / ".codex" / "sessions", HOME / ".codex" / "archived_sessions"]
MACHINE_ID_PATH = HOME / ".domus" / "machine_id"

load_dotenv(ROOT / ".env.local")
load_dotenv(ROOT / ".env")
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
USE_POSTGRES = DATABASE_URL.startswith("postgresql://")


def _machine_id() -> str:
    """Stable identifier for this machine, persisted across runs."""
    MACHINE_ID_PATH.parent.mkdir(parents=True, exist_ok=True)
    if MACHINE_ID_PATH.exists():
        return MACHINE_ID_PATH.read_text().strip()
    mid = str(uuid.uuid4())
    MACHINE_ID_PATH.write_text(mid)
    return mid


MACHINE_ID = _machine_id()

DOMUS_AGENTS = {
    "software-architect", "product-strategist", "copy-strategist",
    "ux-ui-designer", "security-reviewer", "task-ops-manager",
    "devops-release-manager", "workstyle-standards-coordinator",
    "code-reviewer", "test-debugger", "implementation-planner",
}

SCHEMA = """
CREATE TABLE IF NOT EXISTS ingested_files (
    path TEXT PRIMARY KEY,
    mtime REAL NOT NULL,
    size INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS invocations (
    id INTEGER PRIMARY KEY,
    platform TEXT NOT NULL,
    project TEXT,
    branch TEXT,
    agent TEXT NOT NULL,
    session_id TEXT,
    ts TEXT,
    source_file TEXT NOT NULL,
    machine_id TEXT DEFAULT 'local'
);
CREATE TABLE IF NOT EXISTS token_usage (
    id INTEGER PRIMARY KEY,
    platform TEXT NOT NULL,
    project TEXT,
    branch TEXT,
    agent TEXT,
    session_id TEXT,
    ts TEXT,
    model TEXT,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    cache_read_tokens INTEGER DEFAULT 0,
    cache_create_tokens INTEGER DEFAULT 0,
    source_file TEXT NOT NULL,
    machine_id TEXT DEFAULT 'local'
);
CREATE TABLE IF NOT EXISTS agent_map (
    agent_id TEXT PRIMARY KEY,
    agent_type TEXT NOT NULL,
    source_file TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS agent_versions (
    id INTEGER PRIMARY KEY,
    agent TEXT NOT NULL,
    version INTEGER NOT NULL,
    spec_snapshot TEXT NOT NULL,
    spec_hash TEXT NOT NULL,
    diff_summary TEXT,
    platforms TEXT,
    deployed_at TEXT NOT NULL,
    deployed_by TEXT DEFAULT 'local',
    UNIQUE (agent, version)
);
CREATE INDEX IF NOT EXISTS idx_usage_agent ON token_usage(agent);
CREATE INDEX IF NOT EXISTS idx_usage_project ON token_usage(project);
CREATE INDEX IF NOT EXISTS idx_inv_agent ON invocations(agent);
CREATE INDEX IF NOT EXISTS idx_versions_agent ON agent_versions(agent);
CREATE INDEX IF NOT EXISTS idx_versions_deployed_at ON agent_versions(deployed_at);
"""

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS ingested_files (
    path TEXT PRIMARY KEY,
    mtime DOUBLE PRECISION NOT NULL,
    size INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS invocations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL,
    project TEXT,
    branch TEXT,
    agent TEXT NOT NULL,
    session_id TEXT,
    ts TEXT,
    source_file TEXT NOT NULL,
    machine_id TEXT DEFAULT 'local'
);
CREATE TABLE IF NOT EXISTS token_usage (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL,
    project TEXT,
    branch TEXT,
    agent TEXT,
    session_id TEXT,
    ts TEXT,
    model TEXT,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    cache_read_tokens INTEGER DEFAULT 0,
    cache_create_tokens INTEGER DEFAULT 0,
    source_file TEXT NOT NULL,
    machine_id TEXT DEFAULT 'local'
);
CREATE TABLE IF NOT EXISTS agent_map (
    agent_id TEXT PRIMARY KEY,
    agent_type TEXT NOT NULL,
    source_file TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS agent_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent TEXT NOT NULL,
    version INTEGER NOT NULL,
    spec_snapshot TEXT NOT NULL,
    spec_hash TEXT NOT NULL,
    diff_summary TEXT,
    platforms TEXT,
    deployed_at TEXT NOT NULL,
    deployed_by TEXT DEFAULT 'local',
    UNIQUE (agent, version)
);
CREATE INDEX IF NOT EXISTS idx_usage_agent ON token_usage(agent);
CREATE INDEX IF NOT EXISTS idx_usage_project ON token_usage(project);
CREATE INDEX IF NOT EXISTS idx_inv_agent ON invocations(agent);
CREATE INDEX IF NOT EXISTS idx_versions_agent ON agent_versions(agent);
CREATE INDEX IF NOT EXISTS idx_versions_deployed_at ON agent_versions(deployed_at);
"""

# Idempotent migrations for existing databases (new columns added after initial deploy).
SQLITE_MIGRATIONS = [
    "ALTER TABLE invocations ADD COLUMN machine_id TEXT DEFAULT 'local'",
    "ALTER TABLE token_usage ADD COLUMN machine_id TEXT DEFAULT 'local'",
]
POSTGRES_MIGRATIONS = [
    "ALTER TABLE invocations ADD COLUMN IF NOT EXISTS machine_id TEXT DEFAULT 'local'",
    "ALTER TABLE token_usage ADD COLUMN IF NOT EXISTS machine_id TEXT DEFAULT 'local'",
]


class DbCompat:
    def __init__(self, raw, postgres=False):
        self.raw = raw
        self.postgres = postgres

    def executescript(self, script):
        if not self.postgres:
            return self.raw.executescript(script)
        with self.raw.cursor() as cur:
            for stmt in script.split(";"):
                if stmt.strip():
                    cur.execute(stmt)

    def execute(self, sql, params=()):
        if not self.postgres:
            return self.raw.execute(sql, params)
        sql = self._postgres_sql(sql)
        return self.raw.execute(sql, params)

    def executemany(self, sql, params):
        if not params:
            return None
        if not self.postgres:
            return self.raw.executemany(sql, params)
        sql = self._postgres_sql(sql)
        with self.raw.cursor() as cur:
            return cur.executemany(sql, params)

    def commit(self):
        return self.raw.commit()

    def rollback(self):
        return self.raw.rollback()

    def _postgres_sql(self, sql):
        sql = sql.replace("?", "%s")
        if sql.startswith("INSERT OR REPLACE INTO ingested_files"):
            return (
                "INSERT INTO ingested_files(path, mtime, size) VALUES (%s,%s,%s) "
                "ON CONFLICT(path) DO UPDATE SET "
                "mtime=EXCLUDED.mtime, size=EXCLUDED.size"
            )
        if sql.startswith("INSERT OR REPLACE INTO agent_map"):
            return (
                "INSERT INTO agent_map(agent_id, agent_type, source_file) VALUES (%s,%s,%s) "
                "ON CONFLICT(agent_id) DO UPDATE SET "
                "agent_type=EXCLUDED.agent_type, source_file=EXCLUDED.source_file"
            )
        return sql


def connect():
    if USE_POSTGRES:
        if psycopg is None:
            raise RuntimeError("psycopg is required when DATABASE_URL points to Postgres")
        raw = psycopg.connect(DATABASE_URL)
        con = DbCompat(raw, postgres=True)
        try:
            con.execute("SELECT pg_advisory_lock(hashtext(?))", ("domus_agent_usage_schema",))
            con.executescript(POSTGRES_SCHEMA)
            for sql in POSTGRES_MIGRATIONS:
                try:
                    con.execute(sql, ())
                except Exception:
                    # A failed DDL puts psycopg3 in an error state; roll back before
                    # attempting the next migration or the final commit.
                    con.rollback()
            con.commit()
        finally:
            try:
                con.execute("SELECT pg_advisory_unlock(hashtext(?))", ("domus_agent_usage_schema",))
                con.commit()
            except Exception:
                con.rollback()
        return con
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    con = DbCompat(sqlite3.connect(DB_PATH))
    con.executescript(SCHEMA)
    for sql in SQLITE_MIGRATIONS:
        try:
            con.execute(sql, ())
        except Exception:
            pass
    con.commit()
    return con


def file_changed(con, path: Path) -> bool:
    st = path.stat()
    row = con.execute("SELECT mtime, size FROM ingested_files WHERE path=?", (str(path),)).fetchone()
    return row is None or row[0] != st.st_mtime or row[1] != st.st_size


def mark_ingested(con, path: Path):
    st = path.stat()
    con.execute(
        "INSERT OR REPLACE INTO ingested_files(path, mtime, size) VALUES (?,?,?)",
        (str(path), st.st_mtime, st.st_size),
    )


def clear_file_rows(con, path: Path):
    con.execute("DELETE FROM invocations WHERE source_file=?", (str(path),))
    con.execute("DELETE FROM token_usage WHERE source_file=?", (str(path),))


# ---------------------------------------------------------------- Claude Code

def _walk_agent_ids(obj, found):
    """Recursively find {agentId, agentType} pairs anywhere in a record."""
    if isinstance(obj, dict):
        if obj.get("agentId") and obj.get("agentType"):
            found[obj["agentId"]] = obj["agentType"]
        for v in obj.values():
            _walk_agent_ids(v, found)
    elif isinstance(obj, list):
        for v in obj:
            _walk_agent_ids(v, found)


def _insert_usage(con, platform, r, msg, agent, path):
    usage = msg.get("usage")
    if not isinstance(usage, dict):
        return
    con.execute(
        "INSERT INTO token_usage(platform, project, branch, agent, session_id, ts, model,"
        " input_tokens, output_tokens, cache_read_tokens, cache_create_tokens,"
        " source_file, machine_id)"
        " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (platform, r.get("cwd"), r.get("gitBranch"), agent, r.get("sessionId"),
         r.get("timestamp"), msg.get("model"),
         usage.get("input_tokens", 0) or 0,
         usage.get("output_tokens", 0) or 0,
         usage.get("cache_read_input_tokens", 0) or 0,
         usage.get("cache_creation_input_tokens", 0) or 0,
         str(path), MACHINE_ID),
    )


def ingest_claude_file(con, path: Path):
    """Main-session transcript: records Task invocations, the agentId->agentType
    map (used to attribute subagent transcripts), and main-session usage."""
    agent_ids = {}
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                # cheap pre-filter keeps the JSON walk off irrelevant lines
                walk = '"agentId"' in line
                try:
                    r = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if walk:
                    _walk_agent_ids(r, agent_ids)
                msg = r.get("message")
                if not isinstance(msg, dict):
                    continue
                if msg.get("role") == "assistant":
                    _insert_usage(con, "claude", r, msg, None, path)
                for block in msg.get("content") or []:
                    if isinstance(block, dict) and block.get("type") == "tool_use" \
                            and block.get("name") in ("Task", "Agent"):
                        inp = block.get("input") or {}
                        agent = inp.get("subagent_type") or "general-purpose"
                        con.execute(
                            "INSERT INTO invocations(platform, project, branch, agent,"
                            " session_id, ts, source_file, machine_id)"
                            " VALUES ('claude',?,?,?,?,?,?,?)",
                            (r.get("cwd"), r.get("gitBranch"), agent,
                             r.get("sessionId"), r.get("timestamp"), str(path), MACHINE_ID),
                        )
    except OSError:
        return
    for agent_id, agent_type in agent_ids.items():
        con.execute(
            "INSERT OR REPLACE INTO agent_map(agent_id, agent_type, source_file) VALUES (?,?,?)",
            (agent_id, agent_type, str(path)),
        )


def ingest_claude_subagent_file(con, path: Path):
    """Subagent transcript (<session>/subagents/agent-<id>.jsonl): all assistant
    usage is attributed to the agent type resolved via agent_map."""
    agent_id = path.stem.removeprefix("agent-")
    row = con.execute("SELECT agent_type FROM agent_map WHERE agent_id=?", (agent_id,)).fetchone()
    agent = row[0] if row else None
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                try:
                    r = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if agent is None and r.get("agentId"):
                    sub = con.execute(
                        "SELECT agent_type FROM agent_map WHERE agent_id=?",
                        (r["agentId"],)).fetchone()
                    agent = sub[0] if sub else None
                msg = r.get("message")
                if isinstance(msg, dict) and msg.get("role") == "assistant":
                    _insert_usage(con, "claude", r, msg, agent or "unknown-subagent", path)
    except OSError:
        return


# --------------------------------------------------------------------- Codex

def ingest_codex_file(con, path: Path):
    """One Codex rollout = one session.

    token_count events carry cumulative + last-turn usage; we record the
    per-turn delta (last_token_usage). Agent attribution is best-effort:
    Codex skills/agents matching the Domus set are detected from payload text.
    """
    cwd = branch = model = session_id = None
    agents_seen = set()
    usage_rows = []
    invocation_rows = []
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                try:
                    d = json.loads(line)
                except json.JSONDecodeError:
                    continue
                p = d.get("payload") or {}
                t = d.get("type")
                if t == "session_meta":
                    cwd = p.get("cwd") or cwd
                    session_id = p.get("id") or session_id
                    git = p.get("git") or {}
                    branch = git.get("branch") or branch
                elif t == "turn_context":
                    cwd = p.get("cwd") or cwd
                    model = p.get("model") or model
                elif t == "event_msg" and p.get("type") == "token_count":
                    info = p.get("info") or {}
                    last = info.get("last_token_usage") or {}
                    if not last:
                        continue
                    cached = last.get("cached_input_tokens", 0) or 0
                    usage_rows.append(
                        (cwd, branch, None, session_id, d.get("timestamp"), model,
                         (last.get("input_tokens", 0) or 0) - cached,
                         last.get("output_tokens", 0) or 0,
                         cached, str(path), MACHINE_ID)
                    )
                elif t == "response_item":
                    # Detect Domus skill/agent invocations in tool calls.
                    if p.get("type") in ("function_call", "custom_tool_call", "local_shell_call"):
                        blob = json.dumps(p)
                        for a in DOMUS_AGENTS:
                            if a in blob and a not in agents_seen:
                                agents_seen.add(a)
                                invocation_rows.append(
                                    (cwd, branch, a, session_id, d.get("timestamp"), str(path),
                                     MACHINE_ID)
                                )
    except OSError:
        return
    con.executemany(
        "INSERT INTO token_usage(platform, project, branch, agent, session_id, ts,"
        " model, input_tokens, output_tokens, cache_read_tokens, cache_create_tokens,"
        " source_file, machine_id) VALUES ('codex',?,?,?,?,?,?,?,?,?,0,?,?)",
        usage_rows,
    )
    con.executemany(
        "INSERT INTO invocations(platform, project, branch, agent,"
        " session_id, ts, source_file, machine_id)"
        " VALUES ('codex',?,?,?,?,?,?,?)",
        invocation_rows,
    )


# ------------------------------------------------------------------- collect

def _check_thresholds(con) -> list[str]:
    """Return warning strings for threshold violations (runs after collect)."""
    msgs = []
    if USE_POSTGRES:
        ts7  = "CAST(ts AS timestamp) >= now() - (7  * interval '1 day')"
        ts30 = "CAST(ts AS timestamp) >= now() - (30 * interval '1 day')"
    else:
        ts7  = "ts >= datetime('now', '-7 days')"
        ts30 = "ts >= datetime('now', '-30 days')"

    # 1. Cache hit < 70% (all-time, min 10K total input-side tokens)
    try:
        rows = con.execute(
            "SELECT agent,"
            " COALESCE(SUM(cache_read_tokens), 0),"
            " COALESCE(SUM(input_tokens + cache_read_tokens + cache_create_tokens), 0)"
            " FROM token_usage WHERE agent IS NOT NULL"
            " GROUP BY agent"
        ).fetchall()
        for agent, cr, total in rows:
            if total >= 10_000 and (cr / total * 100) < 70:
                msgs.append(f"[CACHE ] {agent}: cache hit {cr/total*100:.0f}% < 70%")
    except Exception:
        pass

    # 2. Tokens/invocation spike > 50% vs all-time average (min 3 recent inv)
    try:
        r_tok = dict(con.execute(
            f"SELECT agent, COALESCE(SUM(output_tokens),0)"
            f" FROM token_usage WHERE agent IS NOT NULL AND {ts7} GROUP BY agent"
        ).fetchall())
        r_inv = dict(con.execute(
            f"SELECT agent, COUNT(*)"
            f" FROM invocations WHERE agent IS NOT NULL AND {ts7} GROUP BY agent"
        ).fetchall())
        h_tok = dict(con.execute(
            "SELECT agent, COALESCE(SUM(output_tokens),0)"
            " FROM token_usage WHERE agent IS NOT NULL GROUP BY agent"
        ).fetchall())
        h_inv = dict(con.execute(
            "SELECT agent, COUNT(*)"
            " FROM invocations WHERE agent IS NOT NULL GROUP BY agent"
        ).fetchall())
        for agent, inv_r in r_inv.items():
            inv_h = h_inv.get(agent, 0)
            if inv_r < 3 or inv_h < 5:
                continue
            avg_r = r_tok.get(agent, 0) / inv_r
            avg_h = h_tok.get(agent, 0) / inv_h
            if avg_h > 0 and avg_r > avg_h * 1.5:
                pct = (avg_r / avg_h - 1) * 100
                msgs.append(
                    f"[SPIKE ] {agent}: {avg_r/1000:.1f}K tok/inv (7d)"
                    f" vs {avg_h/1000:.1f}K histórico (+{pct:.0f}%)"
                )
    except Exception:
        pass

    # 3. Agents inactive for 30 days
    try:
        all_ag = {r[0] for r in con.execute(
            "SELECT DISTINCT agent FROM invocations WHERE agent IS NOT NULL"
        ).fetchall()}
        active = {r[0] for r in con.execute(
            f"SELECT DISTINCT agent FROM invocations WHERE agent IS NOT NULL AND {ts30}"
        ).fetchall()}
        for agent in sorted(all_ag - active):
            msgs.append(f"[INATIVO] {agent}: sem invocações nos últimos 30 dias")
    except Exception:
        pass

    return msgs


def _interleave_jobs(first, second):
    """Alternate platforms so long backfills do not starve either side."""
    jobs = []
    max_len = max(len(first), len(second))
    for idx in range(max_len):
        if idx < len(first):
            jobs.append(first[idx])
        if idx < len(second):
            jobs.append(second[idx])
    return jobs


def collect(args):
    con = connect()
    scanned = ingested = 0
    collect_locked = False

    try:
        if USE_POSTGRES:
            row = con.execute(
                "SELECT pg_try_advisory_lock(hashtext(?))",
                ("domus_agent_usage_collect",),
            ).fetchone()
            collect_locked = bool(row and row[0])
            if not collect_locked:
                raise RuntimeError("another Domus usage collection is already running")

        claude_files = sorted(
            CLAUDE_PROJECTS.glob("*/*.jsonl"),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        ) if CLAUDE_PROJECTS.exists() else []
        claude_subagent_files = sorted(
            CLAUDE_PROJECTS.glob("*/*/subagents/agent-*.jsonl"),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        ) \
            if CLAUDE_PROJECTS.exists() else []
        codex_files = []
        for base in CODEX_SESSION_DIRS:
            if base.exists():
                codex_files.extend(base.rglob("rollout-*.jsonl"))
        codex_files = sorted(codex_files, key=lambda p: p.stat().st_mtime, reverse=True)

        platform = getattr(args, "platform", "all")
        codex_jobs = [(p, ingest_codex_file) for p in codex_files]
        # Main sessions first: they populate agent_map used by subagent attribution.
        claude_jobs = [(p, ingest_claude_file) for p in claude_files]
        claude_jobs.extend((p, ingest_claude_subagent_file) for p in claude_subagent_files)

        if platform == "codex":
            jobs = codex_jobs
        elif platform == "claude":
            jobs = claude_jobs
        else:
            jobs = _interleave_jobs(codex_jobs, claude_jobs)

        for path, fn in jobs:
            scanned += 1
            if not file_changed(con, path):
                continue
            try:
                clear_file_rows(con, path)
                fn(con, path)
                mark_ingested(con, path)
                ingested += 1
                con.commit()
                if args.max_updates and ingested >= args.max_updates:
                    break
            except Exception as exc:
                # Roll back the partial writes for this file so the connection
                # stays usable for the remaining files (critical for psycopg3,
                # which enters InFailedSqlTransaction on any unhandled error).
                con.rollback()
                print(f"Warning: failed to ingest {path}: {exc}", file=__import__('sys').stderr)

        con.commit()
        dest = DATABASE_URL.split("@")[-1] if USE_POSTGRES else str(DB_PATH)
        print(f"Platform: {platform}")
        print(f"Scanned {scanned} files, ingested/updated {ingested}.")
        if args.max_updates:
            print(f"Max updates: {args.max_updates}")
        print(f"Database: {'neon:' if USE_POSTGRES else 'sqlite:'}{dest}")
        print(f"Machine:  {MACHINE_ID}")

        alerts = _check_thresholds(con)
        if alerts:
            print("\n--- Alertas de threshold ---")
            for msg in alerts:
                print(msg)
    finally:
        if USE_POSTGRES and collect_locked:
            try:
                con.execute("SELECT pg_advisory_unlock(hashtext(?))", ("domus_agent_usage_collect",))
                con.commit()
            except Exception:
                con.rollback()


# -------------------------------------------------------------------- report

def fmt(n):
    if n >= 1_000_000:
        return f"{n/1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n/1_000:.1f}K"
    return str(n)


def print_table(headers, rows):
    widths = [len(h) for h in headers]
    rows = [[str(c) for c in r] for r in rows]
    for r in rows:
        for i, c in enumerate(r):
            widths[i] = max(widths[i], len(c))
    line = "  ".join(h.ljust(w) for h, w in zip(headers, widths))
    print(line)
    print("-" * len(line))
    for r in rows:
        print("  ".join(c.ljust(w) for c, w in zip(r, widths)))


def short_project(p):
    if not p:
        return "(unknown)"
    return p.replace("\\", "/").rstrip("/").split("/")[-1]


def report(args):
    con = connect()
    where, params = "", []
    if args.agent:
        where = " AND agent = ?"
        params = [args.agent]

    print("\n=== Invocations per agent (all platforms) ===\n")
    rows = con.execute(
        "SELECT agent, platform, COUNT(*) FROM invocations WHERE 1=1" + where +
        " GROUP BY agent, platform ORDER BY COUNT(*) DESC", params).fetchall()
    print_table(["Agent", "Platform", "Invocations"], rows)

    print("\n=== Token usage per agent (subagent work only) ===\n")
    rows = con.execute(
        "SELECT agent, COUNT(*) AS msgs, SUM(input_tokens), SUM(output_tokens),"
        " SUM(cache_read_tokens), SUM(cache_create_tokens)"
        " FROM token_usage WHERE agent IS NOT NULL" + where +
        " GROUP BY agent ORDER BY SUM(output_tokens) DESC", params).fetchall()
    table = []
    for agent, msgs, inp, out, cr, cc in rows:
        total = (inp or 0) + (cr or 0) + (cc or 0)
        hit = f"{(cr or 0) / total * 100:.0f}%" if total else "-"
        table.append([agent, msgs, fmt(inp or 0), fmt(out or 0), fmt(cr or 0), fmt(cc or 0), hit])
    print_table(["Agent", "Msgs", "Input", "Output", "CacheRead", "CacheCreate", "CacheHit"], table)

    print("\n=== Agent x Project (invocations) ===\n")
    rows = con.execute(
        "SELECT agent, project, COUNT(*) FROM invocations WHERE 1=1" + where +
        " GROUP BY agent, project ORDER BY agent, COUNT(*) DESC", params).fetchall()
    print_table(["Agent", "Project", "Invocations"],
                [[a, short_project(p), c] for a, p, c in rows])

    print("\n=== Session totals per project/platform ===\n")
    rows = con.execute(
        "SELECT platform, project, SUM(input_tokens), SUM(output_tokens),"
        " SUM(cache_read_tokens) FROM token_usage"
        " GROUP BY platform, project ORDER BY platform, SUM(output_tokens) DESC").fetchall()
    print_table(["Platform", "Project", "Input", "Output", "CacheRead"],
                [[pl, short_project(pr), fmt(i or 0), fmt(o or 0), fmt(c or 0)]
                 for pl, pr, i, o, c in rows])
    print()


def main():
    ap = argparse.ArgumentParser(description="Domus agent usage tracker (zero-token, local)")
    sub = ap.add_subparsers(dest="cmd", required=True)
    cp = sub.add_parser("collect", help="incrementally ingest Claude/Codex transcripts")
    cp.add_argument(
        "--platform",
        choices=("all", "claude", "codex"),
        default="all",
        help="limit ingest to one platform; default alternates Codex and Claude",
    )
    cp.add_argument(
        "--max-updates",
        type=int,
        default=0,
        help="stop after updating this many changed files; 0 means no limit",
    )
    rp = sub.add_parser("report", help="print usage report")
    rp.add_argument("--agent", help="filter by agent name")
    args = ap.parse_args()
    if args.cmd == "collect":
        collect(args)
    else:
        report(args)


if __name__ == "__main__":
    main()
